name: Command dispatcher
on:
  issue_comment: # applies to PR and issue comments
    types: [created, edited]

jobs:
  command_dispatch:
    name: Dispatch slash commands
    runs-on: ubuntu-latest
    permissions:
      # keep this limited to read permissions for the content only!
      contents: write
    steps:
      - name: Dispatch
        id: dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ github.token }}
          commands: |
            deploy
            integration-test
            build-docs
  
  